# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: students.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='students.proto',
  package='rs.ac.uns.ftn.isa',
  syntax='proto2',
  serialized_options=b'\n\032rs.ac.uns.ftn.isa.messagesB\013OceneProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0estudents.proto\x12\x11rs.ac.uns.ftn.isa\x1a\x1fgoogle/protobuf/timestamp.proto\"\'\n\x07Predmet\x12\r\n\x05sifra\x18\x01 \x02(\t\x12\r\n\x05naziv\x18\x02 \x02(\t\"`\n\x07Student\x12\x0e\n\x06indeks\x18\x01 \x02(\t\x12\x0b\n\x03ime\x18\x02 \x02(\t\x12\x0f\n\x07prezime\x18\x03 \x02(\t\x12\'\n\x05ocene\x18\x04 \x03(\x0b\x32\x18.rs.ac.uns.ftn.isa.Ocena\"\xa6\x01\n\x05Ocena\x12\n\n\x02id\x18\x01 \x02(\x05\x12+\n\x07predmet\x18\x02 \x02(\x0b\x32\x1a.rs.ac.uns.ftn.isa.Predmet\x12+\n\x07student\x18\x03 \x02(\x0b\x32\x1a.rs.ac.uns.ftn.isa.Student\x12\r\n\x05ocena\x18\x04 \x02(\x05\x12(\n\x04\x64\x61te\x18\x05 \x02(\x0b\x32\x1a.google.protobuf.Timestamp\"8\n\x08Predmeti\x12,\n\x08predmeti\x18\x01 \x03(\x0b\x32\x1a.rs.ac.uns.ftn.isa.Predmet\"8\n\x08Studenti\x12,\n\x08studenti\x18\x01 \x03(\x0b\x32\x1a.rs.ac.uns.ftn.isa.Student\"0\n\x05Ocene\x12\'\n\x05ocene\x18\x01 \x03(\x0b\x32\x18.rs.ac.uns.ftn.isa.OcenaB)\n\x1ars.ac.uns.ftn.isa.messagesB\x0bOceneProtos'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_PREDMET = _descriptor.Descriptor(
  name='Predmet',
  full_name='rs.ac.uns.ftn.isa.Predmet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sifra', full_name='rs.ac.uns.ftn.isa.Predmet.sifra', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='naziv', full_name='rs.ac.uns.ftn.isa.Predmet.naziv', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=109,
)


_STUDENT = _descriptor.Descriptor(
  name='Student',
  full_name='rs.ac.uns.ftn.isa.Student',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='indeks', full_name='rs.ac.uns.ftn.isa.Student.indeks', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ime', full_name='rs.ac.uns.ftn.isa.Student.ime', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prezime', full_name='rs.ac.uns.ftn.isa.Student.prezime', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ocene', full_name='rs.ac.uns.ftn.isa.Student.ocene', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=207,
)


_OCENA = _descriptor.Descriptor(
  name='Ocena',
  full_name='rs.ac.uns.ftn.isa.Ocena',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rs.ac.uns.ftn.isa.Ocena.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='predmet', full_name='rs.ac.uns.ftn.isa.Ocena.predmet', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='student', full_name='rs.ac.uns.ftn.isa.Ocena.student', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ocena', full_name='rs.ac.uns.ftn.isa.Ocena.ocena', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='rs.ac.uns.ftn.isa.Ocena.date', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=376,
)


_PREDMETI = _descriptor.Descriptor(
  name='Predmeti',
  full_name='rs.ac.uns.ftn.isa.Predmeti',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='predmeti', full_name='rs.ac.uns.ftn.isa.Predmeti.predmeti', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=434,
)


_STUDENTI = _descriptor.Descriptor(
  name='Studenti',
  full_name='rs.ac.uns.ftn.isa.Studenti',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='studenti', full_name='rs.ac.uns.ftn.isa.Studenti.studenti', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=436,
  serialized_end=492,
)


_OCENE = _descriptor.Descriptor(
  name='Ocene',
  full_name='rs.ac.uns.ftn.isa.Ocene',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ocene', full_name='rs.ac.uns.ftn.isa.Ocene.ocene', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=494,
  serialized_end=542,
)

_STUDENT.fields_by_name['ocene'].message_type = _OCENA
_OCENA.fields_by_name['predmet'].message_type = _PREDMET
_OCENA.fields_by_name['student'].message_type = _STUDENT
_OCENA.fields_by_name['date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_PREDMETI.fields_by_name['predmeti'].message_type = _PREDMET
_STUDENTI.fields_by_name['studenti'].message_type = _STUDENT
_OCENE.fields_by_name['ocene'].message_type = _OCENA
DESCRIPTOR.message_types_by_name['Predmet'] = _PREDMET
DESCRIPTOR.message_types_by_name['Student'] = _STUDENT
DESCRIPTOR.message_types_by_name['Ocena'] = _OCENA
DESCRIPTOR.message_types_by_name['Predmeti'] = _PREDMETI
DESCRIPTOR.message_types_by_name['Studenti'] = _STUDENTI
DESCRIPTOR.message_types_by_name['Ocene'] = _OCENE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Predmet = _reflection.GeneratedProtocolMessageType('Predmet', (_message.Message,), {
  'DESCRIPTOR' : _PREDMET,
  '__module__' : 'students_pb2'
  # @@protoc_insertion_point(class_scope:rs.ac.uns.ftn.isa.Predmet)
  })
_sym_db.RegisterMessage(Predmet)

Student = _reflection.GeneratedProtocolMessageType('Student', (_message.Message,), {
  'DESCRIPTOR' : _STUDENT,
  '__module__' : 'students_pb2'
  # @@protoc_insertion_point(class_scope:rs.ac.uns.ftn.isa.Student)
  })
_sym_db.RegisterMessage(Student)

Ocena = _reflection.GeneratedProtocolMessageType('Ocena', (_message.Message,), {
  'DESCRIPTOR' : _OCENA,
  '__module__' : 'students_pb2'
  # @@protoc_insertion_point(class_scope:rs.ac.uns.ftn.isa.Ocena)
  })
_sym_db.RegisterMessage(Ocena)

Predmeti = _reflection.GeneratedProtocolMessageType('Predmeti', (_message.Message,), {
  'DESCRIPTOR' : _PREDMETI,
  '__module__' : 'students_pb2'
  # @@protoc_insertion_point(class_scope:rs.ac.uns.ftn.isa.Predmeti)
  })
_sym_db.RegisterMessage(Predmeti)

Studenti = _reflection.GeneratedProtocolMessageType('Studenti', (_message.Message,), {
  'DESCRIPTOR' : _STUDENTI,
  '__module__' : 'students_pb2'
  # @@protoc_insertion_point(class_scope:rs.ac.uns.ftn.isa.Studenti)
  })
_sym_db.RegisterMessage(Studenti)

Ocene = _reflection.GeneratedProtocolMessageType('Ocene', (_message.Message,), {
  'DESCRIPTOR' : _OCENE,
  '__module__' : 'students_pb2'
  # @@protoc_insertion_point(class_scope:rs.ac.uns.ftn.isa.Ocene)
  })
_sym_db.RegisterMessage(Ocene)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
